---
- debug: msg="Using EnMasse git URL - {{ enmasse_git_url }}"

- name: "Retrieve EnMasse {{ enmasse_version }} artifact"
  git:
    repo: "{{ enmasse_git_url }}"
    dest: /tmp/enmasse-{{ enmasse_version }}
    version: "{{ enmasse_version }}"
    force: true

- name: Ensure tmp dir exists
  file:
    path: /tmp/enmasse-{{ enmasse_version }}
    state: directory

- set_fact:
    enmasse_playbook_location: enmasse-"{{ enmasse_version }}"/templates/ansible/playbooks/openshift/deploy_all.yml
    enmasse_inventory_path: /tmp/enmasse-{{ enmasse_version }}/templates/ansible/inventory/
    enmasse_authentication_services: []

- name: Generate EnMasse inventory hosts file
  template:
    src: enmasse_hosts.j2
    dest: "{{ enmasse_inventory_path }}/hosts"

  #hack to work around oc new-app failing when a ns begins with openshift- the ns will begin with openshift- in OSD so that it is hidden from the end user
- name: Adjust project check role when using openshift prefix
  template:
    src: "project_task.yml"
    dest: /tmp/enmasse-{{ enmasse_version }}/templates/ansible/roles/project/tasks/main.yml
    force: yes
  when: ns_prefix != ""

- name: "Provision EnMasse {{ enmasse_version }}"
  shell: ansible-playbook -i {{ enmasse_inventory_path }}/hosts /tmp/{{enmasse_playbook_location}}
  args:
    chdir: "../"

- name: Clean up EnMasse artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/enmasse-{{ enmasse_version }}.tgz
    - /tmp/enmasse-{{ enmasse_version }}.zip
    - /tmp/enmasse-{{ enmasse_version }}
  when: enmasse_clean_artifacts

- set_fact:
    enmasse_rest_route: "{{ hostvars['EVAL_VARS']['openshift_master_url'] }}/apis/enmasse.io"

- name: Retrieve secret for webapp manifest
  shell: oc get secret manifest -n {{ eval_webapp_namespace }} -o jsonpath="{$.data.generated_manifest}"
  register: webapp_secret
  failed_when: webapp_secret.stderr != ""

- set_fact:
    webapp_manifest: "{{ webapp_secret.stdout | b64decode }}"
    new_manifest:
      components: []
      version: "{{ integreatly_version }}"
    new_enmasse:
      name: "enmasse"
      version: "{{ enmasse_version }}"
      host: "{{enmasse_rest_route}}"

- name: "remove old enmasse from new manifest"
  set_fact:
    new_manifest:
      components: "{{ new_manifest.components + [item] }}"
      version: "{{ integreatly_version }}"
  with_items: "{{webapp_manifest.components}}"
  when: item.name != "enmasse"

- name: "add new enmasse to new manifest"
  set_fact:
    new_manifest:
      components: "{{ new_manifest.components + [new_enmasse]}}"
      version: "{{ integreatly_version }}"

- name: "delete web app manifest secret"
  shell: "oc delete secret manifest -n {{ eval_webapp_namespace }}"

- debug: msg="{{ new_manifest | to_json | regex_escape }}"

- name: "recreate web app secret"
  shell: oc create secret generic manifest -n {{ eval_webapp_namespace }} --from-literal=generated_manifest="{{new_manifest | to_json | regex_replace('\"', '\\\"') }}"


- name: Generate AuthenticationService
  template:
    src: authenticationservice.yml.j2
    dest: "/tmp/authenticationservice.yml"

- name: Generate keycloak admin password
  set_fact:
    keycloak_admin_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- name: Create secret with the keycloak credentials
  shell: oc create secret generic -n {{ enmasse_namespace }} keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password={{ keycloak_admin_password }}
  register: secret_exists
  failed_when: secret_exists.stderr != '' and 'AlreadyExists' not in secret_exists.stderr

- name: Label secret
  shell: oc label secret keycloak-credentials -n {{ enmasse_namespace }} app=enmasse
  when: secret_exists.rc == 0

- name: "Create EnMasse AuthenticationService"
  shell: oc create -f /tmp/authenticationservice.yml
  register: authenticationservice_exists
  failed_when: authenticationservice_exists.stderr != '' and 'AlreadyExists' not in authenticationservice_exists.stderr

- name: "Verify EnMasse deployment succeeded"
  shell: sleep 5; oc get pods --namespace {{ enmasse_namespace }}  |  grep  "deploy"
  register: result
  until: not result.stdout
  retries: 50
  delay: 10
  failed_when: result.stdout
  changed_when: False

- name: "redeploy tutorial-web-app"
  shell: "oc rollout latest dc/tutorial-web-app -n {{ eval_webapp_namespace }}"


### SOME PRETTY NASTY PATCHES FROM HERE ON ###

- name: "update standard-controller env vars"
  shell: |
    oc set env -n {{ enmasse_namespace }} --overwrite deployment --selector="infraType=standard" --containers="standard-controller" \
    TEMPLATE_DIR=/opt/templates \
    ENABLE_EVENT_LOGGER=true \
    BROKER_IMAGE=registry.redhat.io/amq-broker-7/amq-broker-72-openshift:latest \
    BROKER_PLUGIN_NAME=registry.redhat.io/amq7/amq-online-1-broker-plugin:1.1 \
    TOPIC_FORWARDER_IMAGE=registry.redhat.io/amq7/amq-online-1-topic-forwarder:1.1 \
    Always=Always

## ENV VARS ENDING IN A - ARE DELETED
- name: "update agent env vars"
  shell: |
    oc set env -n {{ enmasse_namespace }} --overwrite deployment --selector="infraType=standard" --container="agent" \
    AUTHENTICATION_SERVICE_OAUTH_URL- \
    AUTHENTICATION_SERVICE_KC_IDP_HINT- \
    CONSOLE_OAUTH_DISCOVERY_URL=https://openshift.default.svc/.well-known/oauth-authorization-server \
    CONSOLE_OAUTH_SCOPE='user:full' \
    CONSOLE_LINK='https://console-enmasse.{{ apps_redirect_uri }}'

- name: "patch console deploys to read env vars from secret"
  shell: |
    oc patch -n {{ enmasse_namespace }} deployment --selector="infraType=standard" --type=json --patch '[
      {
        "op": "add",
        "path": "/spec/template/spec/containers/1/env/-",
        "value": {
          "name": "CONSOLE_OAUTH_CLIENT_ID",
          "valueFrom": {
            "secretKeyRef": {"key": "client-id", "name": "console-oauth"}
          }
        }
      },
      {
        "op": "add",
        "path": "/spec/template/spec/containers/1/env/-",
        "value": {
          "name": "CONSOLE_OAUTH_CLIENT_SECRET",
          "valueFrom": {
            "secretKeyRef": {"key": "client-secret", "name": "console-oauth"}
          }
        }
      },
        {
          "op": "add",
          "path": "/spec/template/spec/containers/1/env/-",
          "value": {
            "name": "SSO_COOKIE_SECRET",
            "valueFrom": {
              "secretKeyRef": {"key": "cookie-secret", "name": "console-sso-cookie-secret"}
            }
          }
        }
    ]'

- name: "patch console deployments"
  shell: |
    oc patch -n {{ enmasse_namespace }} deployment --selector="infraType=standard" --type=json --patch '[
      {
        "op": "remove",
        "path": "/spec/template/spec/containers/0/volumeMounts/1"
      },
      {
        "op": "replace",
        "path": "/spec/template/spec/containers/1/image",
        "value": "registry.redhat.io/amq7/amq-online-1-agent:1.1"
      },
      {
        "op": "remove",
        "path": "/spec/template/spec/containers/1/volumes/5"
      }
    ]'
