---
- debug: msg="Using EnMasse git URL - {{ enmasse_git_url }}"

- name: "Retrieve EnMasse {{ enmasse_version }} artifact"
  git:
    repo: "{{ enmasse_git_url }}"
    dest: /tmp/enmasse-{{ enmasse_version }}
    version: "{{ enmasse_version }}"
    force: true

- name: Ensure tmp dir exists
  file:
    path: /tmp/enmasse-{{ enmasse_version }}
    state: directory

- set_fact:
    enmasse_playbook_location: enmasse-"{{ enmasse_version }}"/templates/ansible/playbooks/openshift/deploy_all.yml
    enmasse_inventory_path: /tmp/enmasse-{{ enmasse_version }}/templates/ansible/inventory/
    enmasse_authentication_services: []

- name: Generate EnMasse inventory hosts file
  template:
    src: enmasse_hosts.j2
    dest: "{{ enmasse_inventory_path }}/hosts"

  #hack to work around oc new-app failing when a ns begins with openshift- the ns will begin with openshift- in OSD so that it is hidden from the end user
- name: Adjust project check role when using openshift prefix
  template:
    src: "project_task.yml"
    dest: /tmp/enmasse-{{ enmasse_version }}/templates/ansible/roles/project/tasks/main.yml
    force: yes
  when: ns_prefix != ""

- name: "Provision EnMasse {{ enmasse_version }}"
  shell: ansible-playbook -i {{ enmasse_inventory_path }}/hosts /tmp/{{enmasse_playbook_location}}
  args:
    chdir: "../"

- name: Clean up EnMasse artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/enmasse-{{ enmasse_version }}.tgz
    - /tmp/enmasse-{{ enmasse_version }}.zip
    - /tmp/enmasse-{{ enmasse_version }}
  when: enmasse_clean_artifacts

- set_fact:
    enmasse_rest_route: "{{ hostvars['EVAL_VARS']['openshift_master_url'] }}/apis/enmasse.io"

- name: Retrieve secret for webapp manifest
  shell: oc get secret manifest -n {{ eval_webapp_namespace }} -o jsonpath="{$.data.generated_manifest}"
  register: webapp_secret
  failed_when: webapp_secret.stderr != ""

- set_fact:
    webapp_manifest: "{{ webapp_secret.stdout | b64decode }}"
    new_manifest:
      components: []
    new_enmasse:
      name: "enmasse"
      version: "{{ enmasse_version }}"
      host: "{{enmasse_rest_route}}"

- name: "remove old enmasse from new manifest"
  set_fact:
    new_manifest:
      components: "{{ new_manifest.components + [item] }}"
  with_items: "{{webapp_manifest.components}}"
  when: item.name != "enmasse"

- name: "add new enmasse to new manifest"
  set_fact:
    new_manifest:
      components: "{{ new_manifest.components + [new_enmasse]}}"

- name: "delete web app manifest secret"
  shell: "oc delete secret manifest -n {{ eval_webapp_namespace }}"

- name: "recreate web app secret"
  shell: oc create secret generic manifest -n {{ eval_webapp_namespace }} --from-literal=components="{{new_manifest.components | to_json}}"


- name: Generate AuthenticationService
  template:
    src: authenticationservice.yml.j2
    dest: "/tmp/authenticationservice.yml"

- name: Generate keycloak admin password
  set_fact:
    keycloak_admin_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- name: Create secret with the keycloak credentials
  shell: oc create secret generic -n {{ enmasse_namespace }} keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password={{ keycloak_admin_password }}
  register: secret_exists
  failed_when: secret_exists.stderr != '' and 'AlreadyExists' not in secret_exists.stderr

- name: Label secret
  shell: oc label secret keycloak-credentials -n {{ enmasse_namespace }} app=enmasse
  when: secret_exists.rc == 0

- name: "Create EnMasse AuthenticationService"
  shell: oc create -f /tmp/authenticationservice.yml
  register: authenticationservice_exists
  failed_when: authenticationservice_exists.stderr != '' and 'AlreadyExists' not in authenticationservice_exists.stderr

- name: "Verify EnMasse deployment succeeded"
  shell: sleep 5; oc get pods --namespace {{ enmasse_namespace }}  |  grep  "deploy"
  register: result
  until: not result.stdout
  retries: 50
  delay: 10
  failed_when: result.stdout
  changed_when: False

- name: "redeploy tutorial-web-app"
  shell: "oc rollout latest dc/tutorial-web-app -n {{ eval_webapp_namespace }}"

- name: "delete keycloak controller"
  shell: "oc delete -n {{ enmasse_namespace }} dc/keycloak-controller"