---

- hosts: localhost
  gather_facts: yes
  tasks:
  - name: Set Upgrade Facts
    set_fact: upgrade_{{ item }}=true
    with_items: "{{ upgrade_products }}"

  - name: Upgrade products
    include_role:
      name: "{{ item }}"
      tasks_from: "{{ upgrade_tasks_from }}"
    with_items: "{{ upgrade_products }}"
